### PR TITLE
Fix compile in MathEx.cs

### PR DESCRIPTION
**Pull request by lindexi**
## Description

Try fix code encoding

### CODE REVIEW

**Comment by vishalmsft** [comment]
@lindexi What kind of error is this character causing?

**Comment by lindexi** [comment]
@vishalmsft  Should it be `?` ?

My VisualStudio will show error message as below when I open the MathEx.cs file.





Seems to be the encoding error.

**Comment by vishalmsft** [comment]
@lindexi  do you have English language pack installed?

**Comment by lindexi** [comment]
@vishalmsft Sorry, I will install it now.

**Comment by lindexi** [comment]
@vishalmsft I update my VisualStudio with English language pack.

**Comment by vishalmsft** [comment]
@lindexi Can you try the solution suggested at [this ](https://stackoverflow.com/questions/4305923/file-load-some-bytes-have-been-replaced-with-the-unicode-substitution-character) page too?

**Comment by lindexi** [comment]
@vishalmsft  Thank you.

**Pull request closed without merging**
